packageExtensions:
  "react-dev-utils@*":
    peerDependencies:
      "typescript": "*"
      "webpack": "*"
  "babel-preset-react-app@*":
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
